services:
  api:
    image: ghcr.io/danielkinahan/gchat-api:latest
    container_name: gchat-api
    volumes:
      - ./data:/data:ro
      - ./config:/config:ro
    restart: always

  web:
    image: ghcr.io/danielkinahan/gchat-web:latest
    container_name: gchat-web
    ports:
      - "3000:80"
    env_file: .env
    networks:
      - caddy
    restart: always

  scheduler:
    image: ghcr.io/danielkinahan/gchat-scheduler:latest
    container_name: gchat-scheduler
    env_file: .env
    volumes:
      - ./data:/data
      - ./config:/config:ro

networks:
  caddy:
    external: true
    name: caddy
