services:
  api:
    build:
      context: .
      dockerfile: Containerfile.api
    volumes:
      - ./data:/data:ro
      - ./config:/config:ro

  web:
    build:
      context: .
      dockerfile: Containerfile.web
    ports:
      - "3000:80"
    env_file: .env
    depends_on:
      - api

  scheduler:
    build:
      context: .
      dockerfile: Containerfile.scheduler
    env_file: .env
    volumes:
      - ./data:/data
      - ./config:/config:ro
