services:
  api:
    image: ghcr.io/danielkinahan/gchat-api:latest
    container_name: gchat-api
    env_file: .env
    volumes:
      - ./data:/data:ro
      - ./config:/config:ro
    networks:
      - gchat
    restart: always

  web:
    image: ghcr.io/danielkinahan/gchat-web:latest
    container_name: gchat-web
    ports:
      - "3000:80"
    env_file: .env
    networks:
      - caddy
      - gchat
    restart: always

  scheduler:
    image: ghcr.io/danielkinahan/gchat-scheduler:latest
    container_name: gchat-scheduler
    env_file: .env
    networks:
      - gchat
    volumes:
      - ./data:/data
      - ./config:/config:ro

  signal:
    image: lscr.io/linuxserver/signal:latest
    container_name: signal
    environment:
      - HARDEN_DESKTOP=true
      - HARDEN_OPENBOX=true
    volumes:
      - ./data/signal:/config
    shm_size: "1gb"
    restart: always

networks:
  caddy:
    external: true
    name: caddy
  gchat:
    name: gchat
